root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["--config", "config/worker-config.yml"]
  bin = "./tmp/worker"
  cmd = "go build -o ./tmp/worker ./cmd/worker"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "ssl", ".docker", "migrations", "cmd/api", "internal/api", "internal/handlers"]
  exclude_file = [".golangci.yml", ".goreleaser.yml", "config/*.example.yml", "config/config.example.yml"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "yml", "yaml"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
