services:
  mongodb:
    image: mongo:latest
    container_name: ratatoskr-mongodb
    ports:
      - "27017:27017"
    volumes:
      - .docker/data/mongo:/data/db
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: ratatoskr-redis
    ports:
      - "6379:6379"
    volumes:
      - .docker/data/redis:/data
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    container_name: ratatoskr-postgres
    ports:
      - "5432:5432"
    volumes:
      - .docker/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ratatoskr
      POSTGRES_PASSWORD: ratatoskr123
      POSTGRES_DB: ratatoskr
