server:
  name: "ratatoskr-api"
  environment: "development"
  port: 8080
  debug: true
  trusted_proxies:
    - "127.0.0.1"
    - "::1"
  ssl:
    enabled: true
    port: 8443
    cert: "ssl/self-signed.crt"
    key: "ssl/self-signed.key"
database:
  mongo_url: "mongodb://127.0.0.1:27017/ssl"
redis:
  redis_url: "redis://127.0.0.1:6379/0"
