server:
  port: 8443
  debug: true
  ssl:
    enabled: true
    cert: "ssl/cert.pem"
    key: "ssl/key.pem"
database:
  mongo_url: "mongodb://127.0.0.1:27017/ssl"
redis:
  redis_url: "redis://127.0.0.1:6379/0"
alerting:
  slack:
    webhook_url: ""
  telegram:
    bot_token: ""
    chat_id: ""
